leaf = [
    {
      i: "4",
      LOCATION: "Eritrea",
      Renew_Val: "74.89398",
      Code: "ERI",
      ranking: "217",
      gdpcap: "1600",
      population: "5069",
      gdp: "8110400",
      poverty: "Low",
      x: "440",
      y: "690",
      region: "AFRICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Eritrea is one of the poorest countries in the world, due to several factors, including dictatorships, UN sanctions, and border wars. Less than half of Eritreans have access to electricity. Due to the ongoing complexities of the country, we do not have accurate data for its GDP per capita after 2011. Though there is mining in Eritrea, the country does not produce coal, natural gas, or petroleum. Like most Sub-Saharan African countries, Eritrea relies on green energies more than the world average."
    },
    {
      i: "5",
      LOCATION: "Togo",
      Renew_Val: "83.839",
      Code: "TGO",
      ranking: "213",
      gdpcap: "2100",
      population: "7698",
      gdp: "16165800",
      poverty: "Low",
      x: "470",
      y: "720",
      region: "AFRICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Togo is a West African country whose primary industry is agriculture. Because of its domestic stability and international support, Togo has had some considerable economic growth, but that growth may not last long due to unfavourable and unstable political situations. Less than half the population of Togo currently have access to electricity, the majority of whom reside in urban areas."
    },
    {
      i: "6",
      LOCATION: "Ethiopia",
      Renew_Val: "90.89101",
      Code: "ETH",
      ranking: "205",
      gdpcap: "2300",
      population: "106400",
      gdp: "244720000",
      poverty: "Low",
      x: "570",
      y: "745",
      region: "AFRICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Ethiopia is in extreme poverty. Its GDP per capita of around $2300 per year makes it the sixth poorest country among those which we have data for. However, it has been changing for the better-- the once famine-plagued country's GDP per capita had been increasing by around 10% yearly pre-COVID. Just less than half of all Ethiopians, including a third of people living in rural areas, have access to electricity. Though extremely poor, Ethiopia generates most of its energy via hydropower."
    },
    {
      i: "1",
      LOCATION: "Congo, Democratic Republic of the",
      Renew_Val: "97.37576",
      Code: "COD",
      ranking: "226",
      gdpcap: "1100",
      population: "81399",
      gdp: "89538900",
      poverty: "Low",
      x: "615",
      y: "800",
      region: "AFRICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "The Democratic Republic of Congo has the lowest GDP per capita among the countries which we have data for, at merely 1100 dollars per person in 2017. As of 2019, only 9% of its population had access to electricity; in rural areas, that number is close to 0. Despite its poverty, the DRC generates almost all of its electricity via renewable sources, over 99% of which are hydro energy harnessed along the Congo River."
    },
    {
      i: "2",
      LOCATION: "Mozambique",
      Renew_Val: "79.52884",
      Code: "MOZ",
      ranking: "224",
      gdpcap: "1200",
      population: "28649",
      gdp: "34378800",
      poverty: "Low",
      x: "595",
      y: "815",
      region: "AFRICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Mozambique is one of the poorest countries in the world, its GDP per capita of $1200 a year is the second lowest of the countries we have data for, ranking only ahead of DR Congo. Despite the poverty of the country, more than half of Mozambique's urban population has access to electricity. Despite having reserves of coal and natural gas, Mozambique generates almost four-fifth of its energy by harnessing the hydro energies of the Zambezi River."
    },
    {
      i: "3",
      LOCATION: "Niger",
      Renew_Val: "77.16901",
      Code: "NER",
      ranking: "225",
      gdpcap: "1200",
      population: "21602",
      gdp: "25922400",
      poverty: "Low",
      x: "545",
      y: "815",
      region: "AFRICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Niger is the second least developed country in the world as of 2016, according to the rankings made by the United Nations. Its GDP per capita is among the lowest in the world. Its poverty stems primarily from the lack of manufacturing, high population growth, and low levels of education, and has led to problems such as food insecurity and terrorist activities. Despite its large reserves of Uranium, Niger does not produce any nuclear energy."
    },
    {
      i: "8",
      LOCATION: "Tanzania",
      Renew_Val: "84.35101",
      Code: "TZA",
      ranking: "202",
      gdpcap: "2600",
      population: "54660",
      gdp: "142116000",
      poverty: "Low",
      x: "445",
      y: "790",
      region: "AFRICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Tanzania has one of the fastest-growing economies in the world, averaging between 6 to 7% per year between 2009 and 2017. It was primarily due to its exploitation of natural resources and the growth of its tourism. In spite of that, it is still one of the poorest countries in the world. Though Tanzania's reliance on fossil fuels was not excessively high to begin with, it has decreased by a meaningful amount throughout the years."
    },
    {
      i: "24",
      LOCATION: "Nigeria",
      Renew_Val: "76.91483",
      Code: "NGA",
      ranking: "174",
      gdpcap: "4900",
      population: "190873",
      gdp: "935277700",
      poverty: "Low",
      x: "380",
      y: "780",
      region: "AFRICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Nigeria is the largest economy in Sub-Saharan Africa. While its GDP is high, it is mostly driven by the country's large population, not the well-being of the average Nigerian. Nigeria's economic growth had been lacklustre in recent years, because of low oil prices, domestic instability, and poor economic policies. Despite recent efforts to diversify Nigeria's economy, it is still a major producer of petroleum. Less than two-thirds of Nigerians have access to electricity."
    },
    {
      i: "21",
      LOCATION: "Pakistan",
      Renew_Val: "36.25954",
      Code: "PAK",
      ranking: "177",
      gdpcap: "4600",
      population: "207906",
      gdp: "956367600",
      poverty: "Low",
      x: "635",
      y: "235",
      region: "ASIA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Pakistan is a populous but poor country in South Asia. Its poor economic performance, despite having a large English-speaking population, could trace its roots to political disputes and the lack of foreign investment. Shortage of power is also a contributing factor to Pakistan's lack of capital-intensive industries. Curiously, Pakistan essentially does not import energy to solve that problem. More than one-third of Pakistan's electrical power is produced using renewable sources, a majority of which is hydro."
    },
    {
      i: "29",
      LOCATION: "India",
      Renew_Val: "23.16837",
      Code: "IND",
      ranking: "163",
      gdpcap: "6100",
      population: "1338677",
      gdp: "8165929700",
      poverty: "Medidum-Low",
      x: "530",
      y: "275",
      region: "ASIA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "India is the third largest economy in the world by absolute standards, only trailing the USA and China, and the second largest by population. But on a per-capita basis, it is not very well-off, with a small minority of the urban and rural population still not having access to electricity. Green energy used to comprise more than a quarter of India's electricity supply, though that number had decreased slightly in recent years."
    },
    {
      i: "71",
      LOCATION: "China",
      Renew_Val: "9.178692",
      Code: "CHN",
      ranking: "102",
      gdpcap: "16400",
      population: "1421022",
      gdp: "23304760800",
      poverty: "Medium-High",
      x: "710",
      y: "210",
      region: "ASIA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "China has the largest GDP in the world, mostly because of its population-- also the largest in the world. Its GDP per capita, though nowhere near that of a developed country, has been increasing by more than 6% yearly in the past few decades, which is unusually high even among developing nations. Its reliance on green energy had never been too high, and has been on the decrease since the turn of the century. China's reliance on fossil fuel had been decreasing at the same time."
    },
    {
      i: "128",
      LOCATION: "Brunei Darussalam",
      Renew_Val: "0.003659498",
      Code: "BRN",
      ranking: "14",
      gdpcap: "62200",
      population: "424",
      gdp: "26372800",
      poverty: "High",
      x: "715",
      y: "345",
      region: "ASIA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Brunei has one of the higher GDP per capita in the world, though it had not always been the case. Though Brunei is not an OPEC member, about sixty-five percent of its GDP comes from oil and natural gas sales. It is one of the few countries not in the Middle East whose economy relies so heavily on fossil fuel production. Unsurprisingly, fossil fuel consistently makes up more than 99.9% of Brunei's energy production."
    },
    {
      i: "49",
      LOCATION: "Indonesia",
      Renew_Val: "26.79499",
      Code: "IDN",
      ranking: "132",
      gdpcap: "11400",
      population: "264651",
      gdp: "3017021400",
      poverty: "Medidum-Low",
      x: "765",
      y: "430",
      region: "ASIA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Indonesia has the seventh-largest GDP in the world. Its GDP per capita of $11400 per year is just below average. The Indonesian economy had been growing at around 5% a year pre-COVID, implying it could soon dethrone Russia as the sixth-largest economy in the world. Indonesia has nearly completed the task of electrification, with only less than one percent of Indonesians still without power. Renewable sources currently supply just over a quarter of Indonesia's energy needs, though that number has been decreasing over recent years."
    },
    {
      i: "134",
      LOCATION: "Singapore",
      Renew_Val: "1.123753",
      Code: "SGP",
      ranking: "4",
      gdpcap: "93400",
      population: "5708",
      gdp: "533127200",
      poverty: "High",
      x: "810",
      y: "385",
      region: "ASIA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Singapore has the second largest GDP per capita in the world, among the countries we have data for, trailing behind Luxembourg only. The city-state's economy is highly dependent on the financial sector, imported products, and foreign labour. Due to its small size and high density, it is difficult for Singapore to harness large quantities of wind, hydro, or solar energy. As a consequence, renewable energy has never taken a significant part of Singapore's electricity production."
    },
    {
      i: "110",
      LOCATION: "Japan",
      Renew_Val: "5.441419",
      Code: "JPN",
      ranking: "41",
      gdpcap: "41400",
      population: "127503",
      gdp: "5278624200",
      poverty: "High",
      x: "765",
      y: "240",
      region: "ASIA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Japan has been one of the largest economies in the world for more than half a century, though in recent decades the Japanese economy has had very limited growth. Its labour shortage is projected to negatively impact its economy further. Despite producing very little coal, oil, and natural gas, Japan has had a high reliance on fossil fuels historically. Its production of green energies has been pitifully low among nations of similar levels of wealth and social progress."
    },
    {
      i: "120",
      LOCATION: "Kuwait",
      Renew_Val: "0.009120331",
      Code: "KWT",
      ranking: "29",
      gdpcap: "49900",
      population: "4056",
      gdp: "202394400",
      poverty: "High",
      x: "355",
      y: "375",
      region: "GULF",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Kuwait is one of the wealthy oil-producing gulf countries. Its GDP per capita hovers around $50000 per year, though the exact value varies greatly year by year depending on the oil price. Oil is an indispensable part of its economy, providing up to 90% of government revenue. Like many other gulf coast countries, Kuwait produces very little renewable energy. Renewable sources-- mostly wind-- generate less than 0.1% of Kuwait's electrical power."
    },
    {
      i: "109",
      LOCATION: "Bahrain",
      Renew_Val: "0",
      Code: "BHR",
      ranking: "42",
      gdpcap: "40900",
      population: "1494",
      gdp: "61104600",
      poverty: "High",
      x: "425",
      y: "350",
      region: "GULF",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Bahrain is the only country in the world, among those that we have data for, to generate no renewable energy. It is also the only country in the world that relies 100% on fossil fuels for its energy production. It is hardly surprising, considering that oil sales make up 85% of its government revenue. On the contrary, Bahrain is one of the wealthier countries of the world, with GDP growth rates varying wildly year by year due to fluctuating oil prices. "
    },
    {
      i: "92",
      LOCATION: "Oman",
      Renew_Val: "0.001222747",
      Code: "OMN",
      ranking: "70",
      gdpcap: "27300",
      population: "4666",
      gdp: "127381800",
      poverty: "Medium-High",
      x: "475",
      y: "340",
      region: "GULF",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Oman, despite its mediocre levels of wealth, is another oil-producing and oil-dependent Middle Eastern country. Oil generates between 68 and 85 percent of government revenue, depending on the price. Oman has yet to finish the process of electrification, with approximately eight percent of its population yet to have access to electricity as of 2019. Like many other oil producers in that region, Oman consistently produces very little renewable energy."
    },
    {
      i: "132",
      LOCATION: "Qatar",
      Renew_Val: "0.02707411",
      Code: "QAT",
      ranking: "6",
      gdpcap: "85300",
      population: "2725",
      gdp: "232442500",
      poverty: "High",
      x: "445",
      y: "465",
      region: "GULF",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Qatar is one of the wealthiest countries in the world, ranking fourth in GDP per capita among the countries we have data for. Much of Qatar's economy is driven by the oil and gas industries, and considering the number of reserves it has, would remain so in the foreseeable future. Due to low oil prices, Qatar's economic growth has been inconsistent and disappointing in recent years, despite expansions in non-oil sectors of the economy. Qatar almost exclusively uses fossil fuels to generate energy."
    },
    {
      i: "115",
      LOCATION: "Saudi Arabia",
      Renew_Val: "0.009529154",
      Code: "SAU",
      ranking: "35",
      gdpcap: "44300",
      population: "33101",
      gdp: "1466374300",
      poverty: "High",
      x: "405",
      y: "505",
      region: "GULF",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Saudi Arabia is one of the world's largest producers and exporters of oil. The petroleum industries constitute 87% of Saudi Arabia's budget revenues, and as a consequence, its economic performance is closely tied to oil prices. Like many other Middle Eastern oil producers, Saudi Arabia has done next to nothing to decrease the usage of fossil fuels in its electricity production. Due to the country's size and climate, it has some potential for mass solar energy production."
    },
    {
      i: "127",
      LOCATION: "United States",
      Renew_Val: "7.537478",
      Code: "USA",
      ranking: "17",
      gdpcap: "60200",
      population: "325085",
      gdp: "19570117000",
      poverty: "High",
      x: "275",
      y: "400",
      region: "AMERICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "The United States of America has one of the largest economies in the world, backed by its incredible GDP per capita for a country that populous. Its economic growth rate was not particularly high pre-COVID, despite measures taken by presidents Trump and Obama to stimulate the economy. Due to America's large reserves of coal, oil, and natural gas, as well as the relative unpopularity of expensive green energies, renewable energies have yet to take a big part in fuelling America's massive industries. That could change with the passing of the Green New Deal."
    },
    {
      i: "64",
      LOCATION: "Brazil",
      Renew_Val: "42.31983",
      Code: "BRA",
      ranking: "110",
      gdpcap: "14100",
      population: "207834",
      gdp: "2930459400",
      poverty: "Medium-High",
      x: "105",
      y: "515",
      region: "AMERICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Brazil is the sixth most populous country in the world and the most populous in South America. Like many other South American countries, Brazil relies on renewable energy heavily. Though the exact value changes every year, renewable energy typically constitutes between 35 to 45 percent of Brazil's energy supply. Though not an OPEC member, Brazil's oil production is considerable and increasing. Brazil's economic growth had been lacklustre in recent years, despite being a member of BRICS."
    },
    {
      i: "56",
      LOCATION: "Paraguay",
      Renew_Val: "116.5707",
      Code: "PRY",
      ranking: "124",
      gdpcap: "12300",
      population: "6867",
      gdp: "84464100",
      poverty: "Medidum-Low",
      x: "150",
      y: "315",
      region: "AMERICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Paraguay is a fast-growing economy with mediocre levels of GDP per capita. The Paraguayan economy's over-reliance on exports of agricultural products has led to economic downturns, thus the government has taken steps to diversify the economy by attracting manufacturing industries with cheap and clean electricity. Paraguay is the only country in the world to produce 100% of its energy using renewable methods and is even exporting its excess capacity to neighbouring countries."
    },
    {
      i: "75",
      LOCATION: "Mexico",
      Renew_Val: "9.240073",
      Code: "MEX",
      ranking: "95",
      gdpcap: "17900",
      population: "124777",
      gdp: "2233508300",
      poverty: "Medium-High",
      x: "250",
      y: "355",
      region: "AMERICA",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Mexico is a developing country with a large population and GDP. Its GDP per capita of $17900 per year, though higher than the world average, is far below that of a developed nation. Mexico's economic growth rate has been slow in recent years, primarily due to decreasing oil production and some structural economic issues. Being a producer of oil, natural gas, and coal, Mexico relies little on renewable sources for its energy needs."
    },
    {
      i: "122",
      LOCATION: "Germany",
      Renew_Val: "13.32463",
      Code: "DEU",
      ranking: "26",
      gdpcap: "50900",
      population: "82658",
      gdp: "4207292200",
      poverty: "High",
      x: "645",
      y: "480",
      region: "EUROPE",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Germany is the fifth-largest economy in the world and the largest economy in the European Union by a significant margin. Its economic might, however, does not translate to high percentages of renewable energy production. Its reliance on domestically produced coal and imported natural gas is the largest culprit. Germany is projected to decrease its dependence on fossil fuels in the near future due to a multitude of reasons, domestic and international."
    },
    {
      i: "124",
      LOCATION: "Iceland",
      Renew_Val: "88.49532",
      Code: "ISL",
      ranking: "24",
      gdpcap: "52300",
      population: "334",
      gdp: "17468200",
      poverty: "High",
      x: "645",
      y: "570",
      region: "EUROPE",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Iceland is a relatively wealthy country, even among countries of the European Union, despite its fiscal hardships during the recession of 2008. Its economy had been growing rapidly in the years prior to 2020. Because of its location on the Mid-Atlantic Ridge and its sparse population, Iceland is one of the few countries in the world that could supply a third of its domestic electrical demand using geothermal energy. The remaining two-thirds is mostly covered by hydro energy."
    },
    {
      i: "131",
      LOCATION: "Switzerland",
      Renew_Val: "21.30457",
      Code: "CHE",
      ranking: "11",
      gdpcap: "68400",
      population: "8456",
      gdp: "578390400",
      poverty: "High",
      x: "580",
      y: "470",
      region: "EUROPE",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Switzerland is one of the most advanced economies in the world. Its highly competitive economy is sustained by a skilled labour force and a lively financial industry. Its economic growth has slowed down since the recession of 2008. Switzerland's reliance on fossil fuel as an energy source had decreased to near-zero throughout the years. Currently, it primarily relies on nuclear and hydropower for its electricity generation, the former making up one-third and the latter four-seventh of the country's total production."
    },
    {
      i: "90",
      LOCATION: "Russia",
      Renew_Val: "2.583376",
      Code: "RUS",
      ranking: "72",
      gdpcap: "26500",
      population: "145530",
      gdp: "3856545000",
      poverty: "Medium-High",
      x: "530",
      y: "485",
      region: "EUROPE",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Russia was the sixth-largest economy in the world, at least before the current geopolitical complications it has unwisely drawn itself into. Russia was one of the world's largest providers of oil and natural gas, but that status is rapidly being repealed. Despite having many rivers and other freshwater resources, Russia does not rely on hydro, or any other renewable means, to generate electricity. Its percentage of electricity generated using renewable means has been consistently low."
    },
    {
      i: "133",
      LOCATION: "Ireland",
      Renew_Val: "9.522099",
      Code: "IRL",
      ranking: "5",
      gdpcap: "89700",
      population: "4753",
      gdp: "426344100",
      poverty: "High",
      x: "600",
      y: "620",
      region: "EUROPE",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Ireland is one of the wealthiest countries in the world and is simultaneously one of the faster-growing economies. The Irish economy has had a miraculous recovery from the financial and debt crises of 2008-2011 due to EU stimulus packages and high exports, and low corporate taxes. In contrast, its heavy reliance on fossil fuels-- more than 90% of its energy supply came from fossil fuels, as of 2017-- is less than exciting. The Irish are currently pivoting away from natural gas to wind energy."
    },
    {
      i: "135",
      LOCATION: "Luxembourg",
      Renew_Val: "6.991186",
      Code: "LUX",
      ranking: "3",
      gdpcap: "110300",
      population: "592",
      gdp: "65297600",
      poverty: "High",
      x: "565",
      y: "655",
      region: "EUROPE",
      plot1: "plot1.png",
      plot2: "plot2.png",
      plot3: "plot3.png",
      plot4: "plot4.png",
      info: "Luxembourg has, by a significant margin, the highest GDP per capita among the countries in the world. Its economic growth rate had been unstable for a developed nation, mostly due to its small size and its reliance on the volatile banking and financial industries. The average Luxemburger consumes more energy than the average American. Luxembourg imports the majority of its energy, making it somewhat pointless to discuss its energy-production-makeup."
    }
  ]